spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 97002d10-fe93-4b17-bd9b-07bf64d8d15d
        group: cloud-demo-v1
      config:
        server-addr: 127.0.0.1:8848
        namespace: 97002d10-fe93-4b17-bd9b-07bf64d8d15d
        group: cloud-demo-v1
        file-extension: yaml
  config:
    import:
      - nacos:${spring.application.name}.yaml
      - nacos:redis.yaml
mybatis-plus:
  configuration:
    # 指定 MyBatis 使用 StdOutImpl 直接打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl